import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { baseTheme, themes, themeNames, shadows, computeFluidType } from '../src/styles/tokens.js';
import type { ThemeTokens } from '../src/styles/tokens.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = resolve(__dirname, '../src/styles/tokens.css');

function indent(str: string, level: number = 1): string {
  return str.split('\n').map(line => '  '.repeat(level) + line).join('\n');
}

function tokenBlock(tokens: ThemeTokens): string {
  return Object.entries(tokens)
    .map(([key, value]) => `--${key}: ${value};`)
    .join('\n');
}

// Compute fluid type scale
const fluidType = computeFluidType();

// Build CSS
const css = `/* AUTO-GENERATED by scripts/generate-tokens.ts — do not edit manually */
/* Run \`pnpm generate-tokens\` to regenerate */

@layer tokens, themes;

@layer tokens {
  :root {
    /* Fluid typography */
${Object.entries(fluidType).map(([step, value]) => `    --font-size-${step}: ${value};`).join('\n')}

    /* Shadows */
    --shadow-offset: ${shadows.offset};
    --shadow-inset: ${shadows.inset};
  }
}

@layer themes {
  /* Base theme (default) */
  :root {
${indent(tokenBlock(baseTheme), 2)}
  }

  /* Dark theme */
  html.dark {
${indent(tokenBlock(themes.dark), 2)}
  }

  /* Light theme */
  html.light {
${indent(tokenBlock(themes.light), 2)}
  }

  /* Sanity theme (accessibility mode) */
  html.sanity {
${indent(tokenBlock(themes.sanity), 2)}
  }

  /* Hotdog theme */
  html.hotdog {
${indent(tokenBlock(themes.hotdog), 2)}
  }
}
`;

writeFileSync(outPath, css, 'utf-8');
console.log(`Generated ${outPath} (${themeNames.length} themes, ${Object.keys(baseTheme).length} tokens each)`);
