name: Deploy to Cloudflare Pages

on:
    push:
        branches:
            - master
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: false

permissions: {}

jobs:
    ci:
        uses: ./.github/workflows/ci.yml
        permissions:
            contents: read

    deploy:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        needs: ci
        permissions:
            contents: read
            deployments: write
        steps:
            - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

            - uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6.0.3

            - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
              with:
                  node-version: 22
                  cache: 'pnpm'

            - run: pnpm install --frozen-lockfile

            - run: pnpm build

            - name: Deploy
              uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  command: pages deploy dist --project-name=jeffmatson-site
                  gitHubToken: ${{ secrets.GITHUB_TOKEN }}
